/**
 * NOVA CART LOCAL COMMERCE INTELLIGENCE
 * Centralized Platform Operational Constants & Benchmarks
 *
 * Sourced directly from operational audit across 620 partner stores in Bengaluru.
 */

export const PLATFORM_BENCHMARKS = {
  // Volume & Financials
  REGISTERED_CUSTOMERS: 120000,
  ACTIVE_MONTHLY_USERS: 46000,
  MONTHLY_ORDERS: 38500,
  AVERAGE_ORDER_VALUE_INR: 486,
  MONTHLY_REVENUE_INR: 2610000,
  MONTHLY_PROMO_SPEND_INR: 1700000,
  SIX_MONTH_IMPLEMENTATION_BUDGET_INR: 2500000,

  // Retention & Friction Rates
  REPEAT_PURCHASE_RATE_CURRENT: 0.27,
  REPEAT_PURCHASE_RATE_HISTORICAL_PEAK: 0.41,
  ORDER_CANCELLATION_RATE_CURRENT: 0.11,
  ORDER_CANCELLATION_RATE_HISTORICAL_PEAK: 0.06,
  AVERAGE_DELIVERY_MINUTES_CURRENT: 37,
  AVERAGE_DELIVERY_MINUTES_HISTORICAL: 29,
  MONTHLY_SUPPORT_TICKETS_CURRENT: 5900,
  MONTHLY_SUPPORT_TICKETS_HISTORICAL: 3100,

  // Unit Economics Assumptions
  SUPPORT_COST_PER_TICKET_INR: 180,
  REPEAT_RATE_VOLUME_ABSORPTION_FACTOR: 0.75,

  // Store Network
  TOTAL_INDEPENDENT_STORES: 620,
  PILOT_NETWORK_STORES: 12,
  BENGALURU_ZONES: ["Indiranagar", "Koramangala", "HSR Layout", "Jayanagar", "Whitefield"],
} as const;

export const INVENTORY_THRESHOLDS = {
  FRESH_AUDIT_MINUTES: 60,
  STALE_AUDIT_HOURS: 24,
  DEFAULT_SAFETY_STOCK: 5,
  HIGH_CONFIDENCE_THRESHOLD: 75,
  MEDIUM_CONFIDENCE_THRESHOLD: 50,
} as const;

export const ORDER_RISK_THRESHOLDS = {
  HIGH_RISK_SCORE: 65,
  MEDIUM_RISK_SCORE: 35,
} as const;
